global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "banking-system"
    static_configs:
      - targets: ["192.168.100.4:8085"] # TODO: change to the correct IP
    metrics_path: "/metrics"
